#!/usr/bin/make -f
CC = g++
CFLAGS  = -Wall -g
PROG = Return-void

SRCS = main.cpp Game.cpp Menu.cpp Ship.cpp Bullet.cpp Enemy.cpp

LIBS =  -framework OpenGL -framework GLUT -Wno-deprecated-declarations

all: $(PROG)

$(PROG):	$(SRCS)
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS) $(LIBS)

clean:
	rm -f $(PROG) 

